/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { PerformanceSummary } from './PerformanceSummary';
import type { TargetMode } from './TargetMode';
import type { TriggerEntry } from './TriggerEntry';
import type { Verdict } from './Verdict';
/**
 * Top-level decision report. Persisted as both markdown (human-facing) and
 * JSON (machine-readable, for downstream tooling and `reports/index.sqlite`).
 */
export type DecisionReport = {
    /**
     * Days since the model was last trained.
     */
    days_since_last_train: number;
    /**
     * Per-feature PSI values (`feature_name -> PSI`). Empty when training
     * distributions are not available.
     */
    feature_drift: Record<string, number>;
    /**
     * Wall-clock timestamp at which the report was produced.
     */
    generated_at: string;
    /**
     * Number of bars (live records) consumed by the analysis.
     */
    n_bars: number;
    /**
     * Side-by-side live vs holdout performance summary.
     */
    performance_summary: PerformanceSummary;
    /**
     * Free-form recommended next steps. Programmatically generated by
     * `RetrainEvaluator` based on which triggers fired.
     */
    recommended_next_steps: Array<string>;
    target_mode?: (null | TargetMode);
    /**
     * Every trigger's outcome (including no-fires) for full audit.
     */
    triggers: Array<TriggerEntry>;
    /**
     * The verdict. See [`Verdict`].
     */
    verdict: Verdict;
    /**
     * Inclusive end of the analysed live-performance window.
     */
    window_end: string;
    /**
     * Inclusive start of the analysed live-performance window.
     */
    window_start: string;
};

